# Generated by Django 3.2 on 2021-04-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('found_date', models.IntegerField(default=1920)),
                ('stadium', models.CharField(max_length=64)),
                ('stadium_capacity', models.IntegerField(default=45000)),
                ('number_of_titles', models.IntegerField()),
            ],
        ),
    ]
