# Generated by Django 3.2 on 2021-04-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='crest',
            field=models.ImageField(default=None, upload_to='crests'),
        ),
    ]
